# Generated by Django 5.0.3 on 2024-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_no', models.IntegerField()),
                ('designation', models.CharField(choices=[('Man', 'Manager'), ('Sup', 'Supervisor'), ('Sel', 'Seller'), ('Cas', 'Cashier'), ('Cel', 'Cleaner'), ('Sec', 'Security')], max_length=20)),
                ('mobileno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('qty', models.IntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
