# Generated by Django 5.0.3 on 2024-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sdept', models.CharField(max_length=20)),
            ],
        ),
    ]
